---
title: "Berries"
title-block-banner: images/berries-banner.jpg
title-block-banner-color: white
---

Berries in the Pacific Northwest hold an invaluable position in cultivated gardens and wild landscapes. The area, celebrated for its rich soil, temperate climate, and adequate rainfall, is an ideal habitat for a broad spectrum of berry species.

:::{.added-space}
:::

:::{.added-space}
<a href="#ground-cover-list">
<button type="button" class="btn btn-primary">Jump to Plant List</button></a>

:::

## Role in Horticulture

Berries are a cornerstone of horticultural practices in the Pacific Northwest, offering a range of benefits from the home garden to commercial agriculture.

### Nutritional Value

Berries are highly prized for their nutritional content, being rich in vitamins, antioxidants, and fiber. They provide essential health benefits and are a delicious component of the local diet.

### Economic Value

The cultivation of berries, including strawberries, blueberries, and raspberries, represents a significant agricultural activity in the region. It supports local economies through both domestic consumption and export.

### Pollination Support

Berry plants are crucial in supporting pollinators. Their flowers offer nectar and pollen to a wide array of insects, thereby contributing to the health and sustainability of pollination networks.

### Biodiversity

Diverse berry plantings can enhance genetic diversity in agricultural landscapes, reducing vulnerability to pests and diseases and promoting ecological resilience.

## Role in Landscape Design

In addition to their horticultural value, berries offer aesthetic and functional benefits in garden and landscape design.

### Aesthetic Appeal

Berry plants, with their vibrant flowers, lush foliage, and colorful fruit, add visual interest and seasonal beauty to gardens and landscapes.

### Edible Landscape

Incorporating berry plants into landscape designs offers the dual benefit of aesthetic appeal and edible produce, aligning with the principles of edible landscaping and permaculture.

### Wildlife Attraction

Berry plants attract birds, bees, and other wildlife to the garden, creating lively and dynamic outdoor spaces. This not only aids in pollination but also enhances the garden's ecological value.

### Soil Improvement

Like many perennial plants, berry bushes can help improve soil structure and fertility through their root systems and organic matter contribution.

## Role in the Ecosystem

Outside of human cultivation, wild berries play a foundational role in the Pacific Northwest's ecosystems.

### Food Web Support

Berries serve as a vital food source for a variety of wildlife, including birds, bears, and small mammals, thus playing a key role in local food webs.

### Habitat Formation

Thickets of berry plants provide shelter and breeding sites for wildlife, contributing to habitat complexity and diversity.

### Soil Conservation

The root systems of berry plants help stabilize the soil, preventing erosion and promoting soil health in natural landscapes.

## Table of Berry Species for Willamette Valley {#ground-cover-list}

:::{.column-page}

{{< embed jupyter/berries.ipynb#plant-table >}}
:::{.added-space}

:::

:::{.added-space}
::: {.small-font}
##### Soil type
A = any\
C = clay\
CL = clay/loam\
SL = sandy/loam\
WD = well drained\

##### Water requirement 
DT = drought tolerant\
SDT = semi-drought tolerant\
R = regular irrigation\
W  = wet\
F  = tolerates flood\

##### Maintenance
LN = low to none\
M  = moderate\

##### Rate of Growth
R = rapid\
F = fast\
M = moderate\
S = slow\
VS = very slow\

##### Disease Resistance
H = high\
M = moderate\
L = low\

##### Flower Color
W = white\
CRM = cream\
PI  = pink\
Y = yellow\
PU = purple\
R = red\
V = varies\
I = insignificant\
F = fragrant\
B = blue\

##### Propogation
G = graft\
C = cutting\
L = layering\
S = seed\
R = root suckers\

:::
:::
:::