---
title: "Fruit Trees"
title-block-banner: images/fruit-trees-banner.jpg
title-block-banner-color: white
---
Renowned for its temperate climate, and marked by mild, moist winters and warm, dry summers, the Willamette Valley region provides an ideal setting for a diverse array of fruit tree species. These trees not only enrich the diet and support the livelihoods of local communities but also play significant roles in promoting biodiversity, ecological balance, and sustainable land use practices.

:::{.added-space}
:::

:::{.added-space}
<a href="#ground-cover-list">
<button type="button" class="btn btn-primary">Jump to Plant List</button></a>
:::

## Role in Permaculture

In the sphere of permaculture, fruit trees are celebrated for their ability to forge synergies that enhance garden and ecosystem productivity.

### Polyculture and Biodiversity

Fruit trees are keystones in polyculture systems, where their integration with other plants leads to heightened biodiversity. This diversity bolsters ecosystem resilience, mitigating pests and diseases naturally.

### Microclimate Creation

The canopy of fruit trees provides shade, moderates temperature, and shelters underplantings, creating a hospitable microclimate for a myriad of plant species and promoting soil moisture retention.

### Vertical Layering

Fruit trees add a crucial vertical dimension to permaculture designs, allowing for more efficient use of space. This layering technique enables the coexistence of multiple plant species in a single area, optimizing light exposure and nutrient availability.

### Soil Health

The deep root systems of fruit trees help in aerating the soil and cycling nutrients, contributing to the overall health and fertility of the soil. Leaf litter and dropped fruit add organic matter, enhancing soil structure and nutrient content.

### Nutritional Contributions

The fruits borne by these trees are rich in vitamins, minerals, and fibers, offering essential nutritional benefits to human diets and supporting food security.

### Heritage and Cultural Significance

Many fruit tree varieties have historical and cultural significance, reflecting the agricultural heritage of the region. Preserving heirloom varieties contributes to cultural identity and biodiversity.


## Role in Landscape Design

Fruit trees also play a crucial role in landscape design, combining aesthetics with functionality.

### Shade and Structure

The substantial size and canopy of fruit trees provide shade, cooling effects, and structural elements to garden designs, creating comfortable and inviting outdoor spaces.

### Edible Landscaping

Incorporating fruit trees into landscape designs not only beautifies the space but also yields edible rewards, embodying the principles of edible landscaping and sustainability.

## Role in the Ecosystem

Fruit trees contribute significantly to the ecological balance of the Willamette Valley and beyond.

### Wildlife Habitat

Fruit trees offer habitat and food sources for a variety of wildlife, including birds, bees, and other pollinators, enhancing local biodiversity and ecosystem health.

### Carbon Sequestration

By capturing carbon dioxide, fruit trees play a part in mitigating climate change, contributing to the sequestration of carbon and the reduction of greenhouse gas levels in the atmosphere.

### Water Cycle Regulation

Through transpiration and the interception of rainfall, fruit trees play a role in the regulation of the local water cycle, contributing to groundwater recharge and reducing runoff.

## Table of Fruit Tree Species for Willamette Valley {#ground-cover-list}

:::{.column-page}

{{< embed jupyter/fruit-trees.ipynb#plant-table >}}
:::{.added-space}

:::

:::{.added-space}
::: {.small-font}
##### Soil type
A = any\
C = clay\
CL = clay/loam\
SL = sandy/loam\
WD = well drained\

##### Water requirement 
DT = drought tolerant\
SDT = semi-drought tolerant\
R = regular irrigation\
W  = wet\
F  = tolerates flood\

##### Maintenance
LN = low to none\
M  = moderate\

##### Rate of Growth
R = rapid\
F = fast\
M = moderate\
S = slow\
VS = very slow\

##### Disease Resistance
H = high\
M = moderate\
L = low\

##### Flower Color
W = white\
CRM = cream\
PI  = pink\
Y = yellow\
PU = purple\
R = red\
V = varies\
I = insignificant\
F = fragrant\
B = blue\

##### Propogation
G = graft\
C = cutting\
L = layering\
S = seed\
R = root suckers\

:::
:::
:::