---
title: "Nuts"
title-block-banner: images/nut-banner.jpg
title-block-banner-color: white
---
Nuts play an essential role in both agricultural and ecological contexts, particularly in regions like the Pacific Northwest, known for its diverse climates and ecosystems. This area, with its rich soils and varied weather patterns, offers an ideal environment for cultivating a wide range of nut trees, from hazelnuts, which are famously prolific in the region, to walnuts, almonds, and chestnuts. These nut-bearing trees contribute significantly to sustainable farming practices, landscape design, and wildlife support, making them a valuable asset in both rural and urban settings.

:::{.added-space}
:::

:::{.added-space}
<a href="#ground-cover-list">
<button type="button" class="btn btn-primary">Jump to Plant List</button></a>

:::
## Role in Permaculture

In permaculture, nut trees serve multiple valuable functions:

### Economic Value

Nut trees represent a significant agricultural commodity in the Pacific Northwest, particularly hazelnuts, which the region is renowned for globally. These crops provide a stable income for farmers due to the high demand for nuts in both local and international markets.

### Soil Health

Like ground covers, nut trees play a crucial role in maintaining soil health. Their extensive root systems prevent erosion and improve soil structure, facilitating the infiltration of water and the cycling of nutrients.

### Biodiversity

Diverse plantings of nut trees can enhance agricultural biodiversity, creating a more resilient and productive ecosystem. They provide habitat and food for a variety of pollinators and other beneficial wildlife, promoting ecological balance and pest control.

## Role in Landscape Design

Nut trees also have their place in landscape design, offering both aesthetic and functional benefits:

### Shade and Microclimate

Nut trees provide valuable shade, reducing local temperatures and creating comfortable outdoor living spaces. This shade can also contribute to energy savings by cooling buildings and reducing the need for air conditioning in the warmer months.

### Food Production

Incorporating nut trees into residential landscapes or community gardens can provide a sustainable source of food, enhancing food security and encouraging local food systems.

## Role in the Ecosystem

Beyond human-centric benefits, nut trees are integral to the broader ecosystem:

### Wildlife Support

Nut trees offer critical resources for wildlife, including food and nesting sites. Nuts are an important food source for birds, small mammals, and some insects, contributing to ecosystem health and biodiversity.

### Carbon Sequestration

By capturing and storing carbon dioxide through photosynthesis, nut trees play a part in mitigating climate change. Their contribution to carbon sequestration is especially significant given their long lifespans and substantial biomass.

### Water Cycle Regulation

The extensive root systems of nut trees help regulate the water cycle, enhancing groundwater recharge and reducing surface runoff. This contributes to the sustainability of local water resources and the health of aquatic ecosystems.

## Table of Nut Species for Willamette Valley {#ground-cover-list}

:::{.column-page}

{{< embed jupyter/nuts.ipynb#plant-table >}}
:::{.added-space}

:::

:::{.added-space}
::: {.small-font}
##### Soil type
A = any\
C = clay\
CL = clay/loam\
SL = sandy/loam\
WD = well drained\

##### Water requirement 
DT = drought tolerant\
SDT = semi-drought tolerant\
R = regular irrigation\
W  = wet\
F  = tolerates flood\

##### Maintenance
LN = low to none\
M  = moderate\

##### Rate of Growth
R = rapid\
F = fast\
M = moderate\
S = slow\
VS = very slow\

##### Disease Resistance
H = high\
M = moderate\
L = low\

##### Flower Color
W = white\
CRM = cream\
PI  = pink\
Y = yellow\
PU = purple\
R = red\
V = varies\
I = insignificant\
F = fragrant\
B = blue\

##### Propogation
G = graft\
C = cutting\
L = layering\
S = seed\
R = root suckers\

:::
:::
:::