---
title: "Vines"
title-block-banner: images/vines-banner.jpg
title-block-banner-color: white
---
The Pacific Northwest is home to a diverse array of native and adapted vine species. These plants excel in the local climate, contributing significantly to sustainable gardening, agriculture, and ecological restoration efforts.

:::{.added-space}
:::

:::{.added-space}
<a href="#ground-cover-list">
<button type="button" class="btn btn-primary">Jump to Plant List</button></a>

:::

## Role in Permaculture

In permaculture design, vines serve several critical functions that enhance the productivity and sustainability of gardens and ecosystems.

### Vertical Growth

Vines utilize vertical space, offering solutions for small gardens or areas where ground space is limited. They can be trained to grow up trellises, fences, and walls, maximizing the productive use of space.

### Living Structures

Vines can be used to create living structures such as green tunnels, arbors, and pergolas, adding beauty and functionality to garden designs. These structures can provide habitat and support for other species as well.

### Companion Planting

Many vine species can act as beneficial companions to other plants. For example, grapevines can provide shade and moisture retention for understory crops, while some climbing beans can fix nitrogen in the soil, benefiting neighboring plants.

### Role in Landscape Design

Vines are also crucial in landscape design, offering aesthetic and practical benefits.

### Microclimate Creation

Vines can alter microclimates by providing shade and cooling areas during the hot summer months. This can be especially beneficial for creating comfortable outdoor living spaces or for protecting more sensitive plants from intense sun exposure.

### Privacy and Screening
Vines can be used to create natural screens, providing privacy and reducing noise in urban and residential areas. They can quickly cover fences and walls, creating green barriers that enhance the sense of seclusion.

## Role in the Ecosystem

Beyond their use in human-centered landscapes, vines play a foundational role in the Pacific Northwest's ecosystems.

### Habitat and Food
Vines provide essential habitat and food sources for a wide range of wildlife. Many species produce fruits that are vital food sources for birds, mammals, and insects.

### Connectivity
In natural landscapes, vines can act as connectors, linking different parts of the ecosystem together. This can facilitate the movement of species across the landscape, promoting genetic diversity and resilience.

### Erosion Control
Certain types of vines are effective at stabilizing soil and preventing erosion, especially on slopes or areas prone to soil degradation. Their root systems help to hold the soil in place, while their foliage reduces the impact of raindrops.

### Biodiversity
Incorporating a variety of vines into landscapes can support biodiversity by offering a range of habitats, nesting sites, and food sources for birds, insects, and other wildlife.

## Table of Vine Species for Willamette Valley {#ground-cover-list}

:::{.column-page}

{{< embed jupyter/vines.ipynb#plant-table >}}
:::{.added-space}

:::

:::{.added-space}
::: {.small-font}

##### Soil type
A = any\
C = clay\
CL = clay/loam\
SL = sandy/loam\
WD = well drained\

##### Water requirement 
DT = drought tolerant\
SDT = semi-drought tolerant\
R = regular irrigation\
W  = wet\
F  = tolerates flood\

##### Maintenance
LN = low to none\
M  = moderate\

##### Rate of Growth
R = rapid\
F = fast\
M = moderate\
S = slow\
VS = very slow\

##### Disease Resistance
H = high\
M = moderate\
L = low\

##### Flower Color
W = white\
CRM = cream\
PI  = pink\
Y = yellow\
PU = purple\
R = red\
V = varies\
I = insignificant\
F = fragrant\
B = blue\

##### Propogation
G = graft\
C = cutting\
L = layering\
S = seed\
R = root suckers\

:::
:::
:::